/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        void: 'var(--void)',
        'surface-0': 'var(--surface-0)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        dawn: 'var(--dawn)',
        'dawn-80': 'var(--dawn-80)',
        'dawn-70': 'var(--dawn-70)',
        'dawn-50': 'var(--dawn-50)',
        'dawn-40': 'var(--dawn-40)',
        'dawn-30': 'var(--dawn-30)',
        'dawn-15': 'var(--dawn-15)',
        'dawn-08': 'var(--dawn-08)',
        'dawn-04': 'var(--dawn-04)',
        gold: 'var(--gold)',
        'gold-bright': 'var(--gold-bright)',
        'gold-40': 'var(--gold-40)',
        'gold-15': 'var(--gold-15)',
        'gold-10': 'var(--gold-10)',
        'gold-05': 'var(--gold-05)',
        'atreides-mid': 'var(--atreides-mid)',
        'atreides-light': 'var(--atreides-light)',
        'atreides-glow': 'var(--atreides-glow)',
        'atreides-30': 'var(--atreides-30)',
        'atreides-15': 'var(--atreides-15)',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      spacing: {
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
